### ISSUE TITLE
[Feature] Can support headless mode on remote server?

### ISSUE THREAD

**Issue by livilivi** [GrinZero/node-network-devtools#17]
### Desc
Can support headless mode on remote linux server?
got spawn chrome fail now.
```
[node-network-debugger]:  devtool server is listening on port 5271
uncaughtException:  Error: spawn google-chrome ENOENT
    at ChildProcess._handle.onexit (node:internal/child_process:284:19)
    at onErrorNT (node:internal/child_process:477:16)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
  errno: -2,
  code: 'ENOENT',
  syscall: 'spawn google-chrome',
  path: 'google-chrome',
  spawnargs: [
    '--remote-debugging-port=9333',
    'devtools://devtools/bundled/inspector.html?ws=localhost:5271'
  ]
}
```

...

### To Resolve?

...

### Resolutions(Optional)

...

**Comment by GrinZero** [comment]
Hello, I have received your request. As my little cat is constantly harassing me, I will start processing          po[]
           ssssssssssit as soon as possible

**Comment by GrinZero** [comment]
> ### Desc
> Can support headless mode on remote linux server? got spawn chrome fail now.
> 

Hello 👋 Can you explain in detail why headless chrome needs to be run on a remote Linux server? According to my understanding, one of the purposes of using devtool is to visualize network requests.

Even if it supports running, is it meaningful not to see it? Or do you expect to run the monitoring server separately? Instead of pushing data to devtool

**Comment by livilivi** [comment]
> > ### Desc 描述
> > Can support headless mode on remote linux server? got spawn chrome fail now.可以在远程Linux服务器上支持无头模式吗？现在 Spawn chrome 失败了。
> 
> Hello 👋 Can you explain in detail why headless chrome needs to be run on a remote Linux server? According to my understanding, one of the purposes of using devtool is to visualize network requests.你好👋你能详细解释一下为什么headless chrome需要在远程Linux服务器上运行吗？据我了解，使用devtool的目的之一就是将网络请求可视化。
> 
> Even if it supports running, is it meaningful not to see it? Or do you expect to run the monitoring server separately? Instead of pushing data to devtool就算支持跑步，不看还有意义吗？或者您希望单独运行监控服务器？而不是将数据推送到 devtool



> > ### Desc 描述
> > Can support headless mode on remote linux server? got spawn chrome fail now.可以在远程Linux服务器上支持无头模式吗？现在 Spawn chrome 失败了。
> 
> Hello 👋 Can you explain in detail why headless chrome needs to be run on a remote Linux server? According to my understanding, one of the purposes of using devtool is to visualize network requests.你好👋你能详细解释一下为什么headless chrome需要在远程Linux服务器上运行吗？据我了解，使用devtool的目的之一就是将网络请求可视化。
> 
> Even if it supports running, is it meaningful not to see it? Or do you expect to run the monitoring server separately? Instead of pushing data to devtool就算支持跑步，不看还有意义吗？或者您希望单独运行监控服务器？而不是将数据推送到 devtool

I use containers to package my development workspace. Therefore, what needs to be inspected is the node.js middleware in remote development rather than the local node runtime environment.

**Comment by GrinZero** [comment]
Okay, I think I understand what you mean. Actually, what you need is to run the node service on the server/container side. At this point, node network devtools should only start the monitoring server and display the data in the external devtool.

**Comment by livilivi** [comment]
Yep.

**Comment by GrinZero** [comment]
In theory, this is feasible. I will handle it after I go back tonight.
The expected plan is:
1. Add an option to disable automatic opening of Chrome.
2. Add the ability to explicitly specify ports (currently modifiable through environment variables)

In addition to the modifications required by the devtool mentioned above, users themselves also need to make certain modifications: as we are using it in a container, this means we need to release the corresponding port. For example, for Docker, it is necessary to specify `-p 5271:5271`

**Comment by GrinZero** [comment]
Please try v1.0.10

**Comment by livilivi** [comment]
worked great. Thank a lots.
