### ISSUE TITLE
[Feature] Make closeable

### ISSUE THREAD

**Issue by EthianWong** [GrinZero/node-network-devtools#24]
### Desc

In some cases, it may be necessary to dynamically enable and disable network debugging in a production environment, but there is currently no way to disable it. Will keeping it enabled continuously affect performance or memory consumption? Can a method to disable this feature be added?

### To Resolve?

A reasonable cost for implementation makes adding a shutdown feature worthwhile in my opinion.

### Resolutions(Optional)

...

**Comment by GrinZero** [comment]
Hello 👋 May I ask what scenarios require dynamic activation and deactivation of network debugging in the production environment? I strongly do not recommend using `node-network-devtools` in production environments. Before issue #8  is resolved,`node-network-devtools` will store network debugging data based on memory, which can indeed affect performance or cause an increase in memory.

Meanwhile, if you expect dynamic activation, I would recommend using the following code to ensure that it only takes effect in the development environment.
```ts
import { register } from 'node-network-devtools'

process.env.NODE_ENV === 'development' && register()
```

**Comment by EthianWong** [comment]
I agree with your point that `node-network-devtools` should not be used in a production environment.

However, emmm... sometimes reality doesn't match expectations. We are developing a Node.js client-side software (not server-side), and when troubleshooting issues on-site, we hope to observe network requests in a more intuitive way instead of through logs :)

I've made some simple modifications to the code, and it now achieves something similar to an 'unregister' function. From a broad perspective, this might not necessarily be a common requirement, but for a tool, if it can be opened, shouldn't it also be possible to close it? 

Because turning it on will cause performance loss, it can be turned off when not needed (although I can also choose to restart our node program...)

Here are some code snippets.
<img width="810" alt="image" src="https://github.com/user-attachments/assets/8c45920d-c540-4e1f-a29d-d896bade5a00">


If you think this idea is feasible, I can submit a merge request (MR).

**Comment by GrinZero** [comment]
I think this is great! Allow us to proactively eliminate side effects~

**Comment by EthianWong** [comment]
I've committed the MR, and you can review it. Since I'm not very familiar with it, there might be some missed resource releases or rollbacks.

**Comment by GrinZero** [comment]
Right!

**Comment by GrinZero** [comment]
I will confirm and publish after I come back from exercise in the evening
